# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OrderPage.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sqlite3


class Ui_OrderPage(object):
    def Database(self):
        global conn, cursor
        conn = sqlite3.connect("projectdb.db")
        cursor = conn.cursor()
        cursor.execute(
            "CREATE TABLE IF NOT EXISTS `staff` (staff_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, staff_username TEXT, staff_password TEXT, firstName TEXT, lastName TEXT, email TEXT)")
        cursor.execute(
            "CREATE TABLE IF NOT EXISTS 'orders' (order_number INTEGER, staff_id INTEGER, item_name TEXT, item_price INTEGER, item_tax float(4,2), item_category TEXT, item_quantity INTEGER, status TEXT, date DATE, PRIMARY KEY(order_number, item_name))"
        )
        cursor.execute(
            "CREATE TABLE IF NOT EXISTS `admin` (admin_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, admin_username TEXT, admin_password TEXT)")

        cursor.execute("SELECT * FROM `admin` WHERE `admin_username` = 'admin' AND `admin_password` = 'admin'")
        if cursor.fetchone() is None:
            cursor.execute("INSERT INTO `admin` (admin_username, admin_password) VALUES('admin', 'admin')")
            conn.commit()
        cursor.execute("SELECT * FROM `staff`")
        if cursor.fetchone() is None:
            cursor.execute(
                "INSERT INTO `staff` (staff_username, staff_password, firstName, lastName, email) VALUES('FS', 'FS', 'FS', 'FS', 'FS')")
            conn.commit()
    def clearData(self):
        self.CartTable.setRowCount(0)
    def submitData(self):
        products = self.CartTable.rowCount()
        if products == 0:
            qm = QMessageBox()
            qm.setText("Please add some items to the cart to order")
            qm.exec()
        else:

            self.Database()
            cursor.execute(
                "SELECT MAX(order_number) FROM orders;"
            )
            maxOrderNumber2 = cursor.fetchall()[0][0]
            if isinstance(maxOrderNumber2, int) is False:
                maxOrderNumber2 = 0
            else:
                maxOrderNumber2 = int(maxOrderNumber2)
            currentOrderNumber2 = maxOrderNumber2 + 1
            cursor.execute(
                "SELECT date('now');"
            )
            date = cursor.fetchall()[0][0]

            rows = 0
            for individualProduct in range(products):
                cursor.execute(
                    "INSERT INTO orders (order_number, item_name, item_price, item_tax, item_category, item_quantity, status, date) VALUES (?,?,?,?,?,?,?,?);",
                    (currentOrderNumber2, self.CartTable.item(rows, 0).text(), int(self.CartTable.item(rows, 3).text()),
                     self.CartTable.item(rows, 2).text(),
                     self.CartTable.item(rows, 5).text(),
                     int(self.CartTable.item(rows, 1).text()), "Pending", date)
                )
                rows += 1

            cursor.execute("SELECT * FROM orders")
            for each in cursor.fetchall():
                print(each)
            conn.commit()
            qm = QMessageBox()
            qm.setText("Order Submitted Successfully!")
            qm.exec()
            self.clearData()
    def addData(self):
        if len(self.BundlesTable.selectionModel().selectedIndexes()) > 0:
            itemName = self.BundlesTable.item(self.BundlesTable.currentRow(), 0).text()
            itemCategory = self.BundlesTable.item(self.BundlesTable.currentRow(), 1).text()
            itemDescription = self.BundlesTable.item(self.BundlesTable.currentRow(), 2).text()
            itemPrice = int(self.BundlesTable.item(self.BundlesTable.currentRow(), 3).text())
            itemTax = self.BundlesTable.item(self.BundlesTable.currentRow(), 4).text()
            itemTaxValue = float(itemTax[0:itemTax.find('%')])
            rowCount = self.CartTable.rowCount()

            repeated = False
            for each in range(rowCount):
                if self.CartTable.item(each, 0).text() == itemName:
                    quantity = int(self.CartTable.item(each, 1).text())
                    quantity += 1
                    self.CartTable.setItem(each, 1, QtWidgets.QTableWidgetItem(str(quantity)))
                    self.CartTable.setItem(each,4, QtWidgets.QTableWidgetItem(str(quantity * (itemPrice+(itemPrice*(itemTaxValue/100))))))
                    repeated = True

            if not repeated:
                newRowCount = rowCount + 1
                self.CartTable.setRowCount(newRowCount)
                self.CartTable.setItem(newRowCount - 1, 0, QtWidgets.QTableWidgetItem(itemName))
                self.CartTable.setItem(newRowCount - 1, 1, QtWidgets.QTableWidgetItem(str(1)))
                self.CartTable.setItem(newRowCount - 1, 2, QtWidgets.QTableWidgetItem(itemTax))
                self.CartTable.setItem(newRowCount - 1, 3, QtWidgets.QTableWidgetItem(str(itemPrice)))
                self.CartTable.setItem(newRowCount - 1, 4, QtWidgets.QTableWidgetItem(str(itemPrice+(itemPrice*(itemTaxValue/100)))))
                self.CartTable.setItem(newRowCount - 1, 5, QtWidgets.QTableWidgetItem(itemCategory))
            self.BundlesTable.selectionModel().clearSelection()
        elif len(self.MainMealTable.selectionModel().selectedIndexes()) > 0:
            itemName = self.MainMealTable.item(self.MainMealTable.currentRow(), 0).text()
            itemCategory = self.MainMealTable.item(self.MainMealTable.currentRow(), 1).text()
            itemDescription = self.MainMealTable.item(self.MainMealTable.currentRow(), 2).text()
            itemPrice = int(self.MainMealTable.item(self.MainMealTable.currentRow(), 3).text())
            itemTax = self.MainMealTable.item(self.MainMealTable.currentRow(), 4).text()
            itemTaxValue = float(itemTax[0:itemTax.find('%')])
            rowCount = self.CartTable.rowCount()

            repeated = False
            for each in range(rowCount):
                if self.CartTable.item(each, 0).text() == itemName:
                    quantity = int(self.CartTable.item(each, 1).text())
                    quantity += 1
                    self.CartTable.setItem(each, 1, QtWidgets.QTableWidgetItem(str(quantity)))
                    self.CartTable.setItem(each, 4, QtWidgets.QTableWidgetItem(
                        str(quantity * (itemPrice + (itemPrice * (itemTaxValue / 100))))))
                    repeated = True

            if not repeated:
                newRowCount = rowCount + 1
                self.CartTable.setRowCount(newRowCount)
                self.CartTable.setItem(newRowCount - 1, 0, QtWidgets.QTableWidgetItem(itemName))
                self.CartTable.setItem(newRowCount - 1, 1, QtWidgets.QTableWidgetItem(str(1)))
                self.CartTable.setItem(newRowCount - 1, 2, QtWidgets.QTableWidgetItem(itemTax))
                self.CartTable.setItem(newRowCount - 1, 3, QtWidgets.QTableWidgetItem(str(itemPrice)))
                self.CartTable.setItem(newRowCount - 1, 4,
                                       QtWidgets.QTableWidgetItem(str(itemPrice + (itemPrice * (itemTaxValue / 100)))))
                self.CartTable.setItem(newRowCount - 1, 5, QtWidgets.QTableWidgetItem(itemCategory))
            self.MainMealTable.selectionModel().clearSelection()
        elif len(self.DesertsTable.selectionModel().selectedIndexes()) > 0:
            itemName = self.DesertsTable.item(self.DesertsTable.currentRow(), 0).text()
            itemCategory = self.DesertsTable.item(self.DesertsTable.currentRow(), 1).text()
            itemDescription = self.DesertsTable.item(self.DesertsTable.currentRow(), 2).text()
            itemPrice = int(self.DesertsTable.item(self.DesertsTable.currentRow(), 3).text())
            itemTax = self.DesertsTable.item(self.DesertsTable.currentRow(), 4).text()
            itemTaxValue = float(itemTax[0:itemTax.find('%')])
            rowCount = self.CartTable.rowCount()

            repeated = False
            for each in range(rowCount):
                if self.CartTable.item(each, 0).text() == itemName:
                    quantity = int(self.CartTable.item(each, 1).text())
                    quantity += 1
                    self.CartTable.setItem(each, 1, QtWidgets.QTableWidgetItem(str(quantity)))
                    self.CartTable.setItem(each, 4, QtWidgets.QTableWidgetItem(
                        str(quantity * (itemPrice + (itemPrice * (itemTaxValue / 100))))))
                    repeated = True

            if not repeated:
                newRowCount = rowCount + 1
                self.CartTable.setRowCount(newRowCount)
                self.CartTable.setItem(newRowCount - 1, 0, QtWidgets.QTableWidgetItem(itemName))
                self.CartTable.setItem(newRowCount - 1, 1, QtWidgets.QTableWidgetItem(str(1)))
                self.CartTable.setItem(newRowCount - 1, 2, QtWidgets.QTableWidgetItem(itemTax))
                self.CartTable.setItem(newRowCount - 1, 3, QtWidgets.QTableWidgetItem(str(itemPrice)))
                self.CartTable.setItem(newRowCount - 1, 4,
                                       QtWidgets.QTableWidgetItem(str(itemPrice + (itemPrice * (itemTaxValue / 100)))))
                self.CartTable.setItem(newRowCount - 1, 5, QtWidgets.QTableWidgetItem(itemCategory))
            self.DesertsTable.selectionModel().clearSelection()
        elif len(self.DrinksTable.selectionModel().selectedIndexes()) > 0:
            itemName = self.DrinksTable.item(self.DrinksTable.currentRow(), 0).text()
            itemCategory = self.DrinksTable.item(self.DrinksTable.currentRow(), 1).text()
            itemDescription = self.DrinksTable.item(self.DrinksTable.currentRow(), 2).text()
            itemPrice = int(self.DrinksTable.item(self.DrinksTable.currentRow(), 3).text())
            itemTax = self.DrinksTable.item(self.DrinksTable.currentRow(), 4).text()
            itemTaxValue = float(itemTax[0:itemTax.find('%')])
            rowCount = self.CartTable.rowCount()

            repeated = False
            for each in range(rowCount):
                if self.CartTable.item(each, 0).text() == itemName:
                    quantity = int(self.CartTable.item(each, 1).text())
                    quantity += 1
                    self.CartTable.setItem(each, 1, QtWidgets.QTableWidgetItem(str(quantity)))
                    self.CartTable.setItem(each, 4, QtWidgets.QTableWidgetItem(
                        str(quantity * (itemPrice + (itemPrice * (itemTaxValue / 100))))))
                    repeated = True

            if not repeated:
                newRowCount = rowCount + 1
                self.CartTable.setRowCount(newRowCount)
                self.CartTable.setItem(newRowCount - 1, 0, QtWidgets.QTableWidgetItem(itemName))
                self.CartTable.setItem(newRowCount - 1, 1, QtWidgets.QTableWidgetItem(str(1)))
                self.CartTable.setItem(newRowCount - 1, 2, QtWidgets.QTableWidgetItem(itemTax))
                self.CartTable.setItem(newRowCount - 1, 3, QtWidgets.QTableWidgetItem(str(itemPrice)))
                self.CartTable.setItem(newRowCount - 1, 4,
                                       QtWidgets.QTableWidgetItem(str(itemPrice + (itemPrice * (itemTaxValue / 100)))))
                self.CartTable.setItem(newRowCount - 1, 5, QtWidgets.QTableWidgetItem(itemCategory))
            self.DrinksTable.selectionModel().clearSelection()
        elif len(self.SnacksTable.selectionModel().selectedIndexes()) > 0:
            itemName = self.SnacksTable.item(self.SnacksTable.currentRow(), 0).text()
            itemCategory = self.SnacksTable.item(self.SnacksTable.currentRow(), 1).text()
            itemDescription = self.SnacksTable.item(self.SnacksTable.currentRow(), 2).text()
            itemPrice = int(self.SnacksTable.item(self.SnacksTable.currentRow(), 3).text())
            itemTax = self.SnacksTable.item(self.SnacksTable.currentRow(), 4).text()
            itemTaxValue = float(itemTax[0:itemTax.find('%')])
            rowCount = self.CartTable.rowCount()

            repeated = False
            for each in range(rowCount):
                if self.CartTable.item(each, 0).text() == itemName:
                    quantity = int(self.CartTable.item(each, 1).text())
                    quantity += 1
                    self.CartTable.setItem(each, 1, QtWidgets.QTableWidgetItem(str(quantity)))
                    self.CartTable.setItem(each, 4, QtWidgets.QTableWidgetItem(
                        str(quantity * (itemPrice + (itemPrice * (itemTaxValue / 100))))))
                    repeated = True

            if not repeated:
                newRowCount = rowCount + 1
                self.CartTable.setRowCount(newRowCount)
                self.CartTable.setItem(newRowCount - 1, 0, QtWidgets.QTableWidgetItem(itemName))
                self.CartTable.setItem(newRowCount - 1, 1, QtWidgets.QTableWidgetItem(str(1)))
                self.CartTable.setItem(newRowCount - 1, 2, QtWidgets.QTableWidgetItem(itemTax))
                self.CartTable.setItem(newRowCount - 1, 3, QtWidgets.QTableWidgetItem(str(itemPrice)))
                self.CartTable.setItem(newRowCount - 1, 4,
                                       QtWidgets.QTableWidgetItem(str(itemPrice + (itemPrice * (itemTaxValue / 100)))))
                self.CartTable.setItem(newRowCount - 1, 5, QtWidgets.QTableWidgetItem(itemCategory))
            self.SnacksTable.selectionModel().clearSelection()
        else:
            qm = QMessageBox()
            qm.setText("No items have been selected!")
            qm.exec()
    def setupUi(self, OrderPage):
        OrderPage.setObjectName("OrderPage")
        OrderPage.resize(1180, 801)
        OrderPage.setStyleSheet("QPushButton {\n"
                                 "background-color: #FF9A00;\n"
                                 "font: 63 12pt \"Segoe UI Semibold\";\n"
                                 "color: rgb(255, 255, 255);\n"
                                 "border-color: rgb(255, 255, 255);\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(OrderPage)
        self.centralwidget.setObjectName("centralwidget")
        self.OrderBG = QtWidgets.QLabel(self.centralwidget)
        self.OrderBG.setGeometry(QtCore.QRect(0, 0, 1181, 901))
        self.OrderBG.setStyleSheet("background-image: url(:/OrderBG/img/bg/OrderBG.png)")
        self.OrderBG.setText("")
        self.OrderBG.setObjectName("OrderBG")
        self.OrderTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.OrderTabs.setGeometry(QtCore.QRect(20, 180, 601, 601))
        self.OrderTabs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.OrderTabs.setStyleSheet("QTabWidget::pane {\n"
                                     "    border: 1px solid black;\n"
                                     "    background: white;\n"
                                     "}\n"
                                     "\n"
                                     "QTabWidget::tab-bar:top {\n"
                                     "    top: 1px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabWidget::tab-bar:bottom {\n"
                                     "    bottom: 1px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabWidget::tab-bar:left {\n"
                                     "    right: 1px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabWidget::tab-bar:right {\n"
                                     "    left: 1px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab {\n"
                                     "    border: 1px solid black;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:selected {\n"
                                     "    background: #F25234;\n"
                                     "    color: white;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:!selected {\n"
                                     "    background: #FF9A00;\n"
                                     "    color: white;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:!selected:hover {\n"
                                     "    background: #48C0A8;\n"
                                     "    color: white;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:top:!selected {\n"
                                     "    margin-top: 3px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:bottom:!selected {\n"
                                     "    margin-bottom: 3px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:top, QTabBar::tab:bottom {\n"
                                     "    min-width: 8ex;\n"
                                     "    margin-right: -1px;\n"
                                     "    padding: 5px 10px 5px 10px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:top:selected {\n"
                                     "    border-bottom-color: none;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:bottom:selected {\n"
                                     "    border-top-color: none;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
                                     "QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
                                     "    margin-right: 0;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:left:!selected {\n"
                                     "    margin-right: 3px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:right:!selected {\n"
                                     "    margin-left: 3px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:left, QTabBar::tab:right {\n"
                                     "    min-height: 8ex;\n"
                                     "    margin-bottom: -1px;\n"
                                     "    padding: 10px 5px 10px 5px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:left:selected {\n"
                                     "    border-left-color: none;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:right:selected {\n"
                                     "    border-right-color: none;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
                                     "QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
                                     "    margin-bottom: 0;\n"
                                     "}")
        self.OrderTabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.OrderTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.OrderTabs.setIconSize(QtCore.QSize(45, 50))
        self.OrderTabs.setElideMode(QtCore.Qt.ElideLeft)
        self.OrderTabs.setDocumentMode(False)
        self.OrderTabs.setObjectName("OrderTabs")
        self.MainMeal = QtWidgets.QWidget()
        self.MainMeal.setObjectName("MainMeal")
        self.MainMealTable = QtWidgets.QTableWidget(self.MainMeal)
        self.MainMealTable.setGeometry(QtCore.QRect(0, 0, 541, 601))
        self.MainMealTable.setObjectName("MainMealTable")
        self.MainMealTable.setColumnCount(5)
        self.MainMealTable.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainMealTable.setItem(9, 4, item)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/img/Dinner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OrderTabs.addTab(self.MainMeal, icon, "")
        self.Drinks = QtWidgets.QWidget()
        self.Drinks.setObjectName("Drinks")
        self.DrinksTable = QtWidgets.QTableWidget(self.Drinks)
        self.DrinksTable.setGeometry(QtCore.QRect(0, 0, 541, 601))
        self.DrinksTable.setObjectName("DrinksTable")
        self.DrinksTable.setColumnCount(5)
        self.DrinksTable.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(13, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(14, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DrinksTable.setItem(14, 4, item)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/img/Drinks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OrderTabs.addTab(self.Drinks, icon1, "")
        self.Snacks = QtWidgets.QWidget()
        self.Snacks.setObjectName("Snacks")
        self.SnacksTable = QtWidgets.QTableWidget(self.Snacks)
        self.SnacksTable.setGeometry(QtCore.QRect(0, 0, 541, 601))
        self.SnacksTable.setObjectName("SnacksTable")
        self.SnacksTable.setColumnCount(5)
        self.SnacksTable.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SnacksTable.setItem(3, 4, item)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/img/Snacks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OrderTabs.addTab(self.Snacks, icon2, "")
        self.Deserts = QtWidgets.QWidget()
        self.Deserts.setObjectName("Deserts")
        self.DesertsTable = QtWidgets.QTableWidget(self.Deserts)
        self.DesertsTable.setGeometry(QtCore.QRect(0, 0, 541, 601))
        self.DesertsTable.setObjectName("DesertsTable")
        self.DesertsTable.setColumnCount(5)
        self.DesertsTable.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DesertsTable.setItem(3, 4, item)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/img/Deserts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OrderTabs.addTab(self.Deserts, icon3, "")
        self.Bundles = QtWidgets.QWidget()
        self.Bundles.setObjectName("Bundles")
        self.BundlesTable = QtWidgets.QTableWidget(self.Bundles)
        self.BundlesTable.setGeometry(QtCore.QRect(0, 0, 541, 601))
        self.BundlesTable.setObjectName("BundlesTable")
        self.BundlesTable.setColumnCount(5)
        self.BundlesTable.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.BundlesTable.setItem(13, 4, item)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/img/Combo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OrderTabs.addTab(self.Bundles, icon4, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(640, 180, 501, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Cart = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Cart.setContentsMargins(0, 0, 0, 0)
        self.Cart.setObjectName("Cart")
        self.CartTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.CartTable.setColumnCount(6)
        self.CartTable.setObjectName("CartTable")
        self.CartTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CartTable.setHorizontalHeaderItem(5, item)
        self.Cart.addWidget(self.CartTable)
        self.ButtonBox = QtWidgets.QHBoxLayout()
        self.ButtonBox.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ButtonBox.setObjectName("ButtonBox")
        self.RegisterButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RegisterButton_2.setMinimumSize(QtCore.QSize(50, 40))
        self.RegisterButton_2.setObjectName("RegisterButton_2")
        self.ButtonBox.addWidget(self.RegisterButton_2)
        self.LoginButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.LoginButton.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.LoginButton.setFont(font)
        self.LoginButton.setStyleSheet("")
        self.LoginButton.setFlat(False)
        self.LoginButton.setObjectName("LoginButton")
        self.ButtonBox.addWidget(self.LoginButton)
        self.RegisterButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RegisterButton.setMinimumSize(QtCore.QSize(50, 40))
        self.RegisterButton.setObjectName("RegisterButton")
        self.ButtonBox.addWidget(self.RegisterButton)
        self.Cart.addLayout(self.ButtonBox)
        self.LoginTitle = QtWidgets.QLabel(self.centralwidget)
        self.LoginTitle.setGeometry(QtCore.QRect(430, 50, 391, 91))
        self.LoginTitle.setStyleSheet("font: 87 26pt \"Segoe UI\";")
        self.LoginTitle.setObjectName("LoginTitle")
        OrderPage.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrderPage)
        self.OrderTabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(OrderPage)
        self.RegisterButton_2.clicked.connect(self.addData)
        self.RegisterButton.clicked.connect(self.clearData)
        self.LoginButton.clicked.connect(self.submitData)

    def retranslateUi(self, OrderPage):
        _translate = QtCore.QCoreApplication.translate
        OrderPage.setWindowTitle(_translate("OrderPage", "OrderPage"))
        item = self.MainMealTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderPage", "Item Name"))
        item = self.MainMealTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderPage", "Item Category"))
        item = self.MainMealTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderPage", "Item Description"))
        item = self.MainMealTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderPage", "Item Price"))
        item = self.MainMealTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderPage", "Item Tax"))
        __sortingEnabled = self.MainMealTable.isSortingEnabled()
        self.MainMealTable.setSortingEnabled(False)
        item = self.MainMealTable.item(0, 0)
        item.setText(_translate("OrderPage", "Chicken"))
        item = self.MainMealTable.item(0, 1)
        item.setText(_translate("OrderPage", "Main Meal"))
        item = self.MainMealTable.item(0, 2)
        item.setText(_translate("OrderPage", "Main Course"))
        item = self.MainMealTable.item(0, 3)
        item.setText(_translate("OrderPage", "300"))
        item = self.MainMealTable.item(0, 4)
        item.setText(_translate("OrderPage", "3%"))
        item = self.MainMealTable.item(1, 0)
        item.setText(_translate("OrderPage", "Chicken Tikka"))
        item = self.MainMealTable.item(1, 1)
        item.setText(_translate("OrderPage", "Main Meal"))
        item = self.MainMealTable.item(1, 2)
        item.setText(_translate("OrderPage", "Kabab "))
        item = self.MainMealTable.item(1, 3)
        item.setText(_translate("OrderPage", "150"))
        item = self.MainMealTable.item(1, 4)
        item.setText(_translate("OrderPage", "1.5%"))
        item = self.MainMealTable.item(2, 0)
        item.setText(_translate("OrderPage", "Chicken Fajita"))
        item = self.MainMealTable.item(2, 1)
        item.setText(_translate("OrderPage", "Main Meal"))
        item = self.MainMealTable.item(2, 2)
        item.setText(_translate("OrderPage", "Kabab"))
        item = self.MainMealTable.item(2, 3)
        item.setText(_translate("OrderPage", "150"))
        item = self.MainMealTable.item(2, 4)
        item.setText(_translate("OrderPage", "1.5%"))
        item = self.MainMealTable.item(3, 0)
        item.setText(_translate("OrderPage", "Bar B Q Chicken"))
        item = self.MainMealTable.item(3, 1)
        item.setText(_translate("OrderPage", "Main Meal"))
        item = self.MainMealTable.item(3, 2)
        item.setText(_translate("OrderPage", "Main Course"))
        item = self.MainMealTable.item(3, 3)
        item.setText(_translate("OrderPage", "200"))
        item = self.MainMealTable.item(3, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.MainMealTable.item(4, 0)
        item.setText(_translate("OrderPage", "Chicken Pineapple"))
        item = self.MainMealTable.item(4, 1)
        item.setText(_translate("OrderPage", "Main Meal"))
        item = self.MainMealTable.item(4, 2)
        item.setText(_translate("OrderPage", "Main Course"))
        item = self.MainMealTable.item(4, 3)
        item.setText(_translate("OrderPage", "250"))
        item = self.MainMealTable.item(4, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.MainMealTable.item(5, 0)
        item.setText(_translate("OrderPage", "Vegetable"))
        item = self.MainMealTable.item(5, 1)
        item.setText(_translate("OrderPage", "Main Meal"))
        item = self.MainMealTable.item(5, 2)
        item.setText(_translate("OrderPage", "Main Course"))
        item = self.MainMealTable.item(5, 3)
        item.setText(_translate("OrderPage", "250"))
        item = self.MainMealTable.item(5, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.MainMealTable.item(6, 0)
        item.setText(_translate("OrderPage", "Pepperoni"))
        item = self.MainMealTable.item(6, 1)
        item.setText(_translate("OrderPage", "Main Meal"))
        item = self.MainMealTable.item(6, 2)
        item.setText(_translate("OrderPage", "Appetizer"))
        item = self.MainMealTable.item(6, 3)
        item.setText(_translate("OrderPage", "250"))
        item = self.MainMealTable.item(6, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.MainMealTable.item(7, 0)
        item.setText(_translate("OrderPage", "Fish"))
        item = self.MainMealTable.item(7, 1)
        item.setText(_translate("OrderPage", "Main Meal"))
        item = self.MainMealTable.item(7, 2)
        item.setText(_translate("OrderPage", "Main Course"))
        item = self.MainMealTable.item(7, 3)
        item.setText(_translate("OrderPage", "300"))
        item = self.MainMealTable.item(7, 4)
        item.setText(_translate("OrderPage", "3%"))
        item = self.MainMealTable.item(8, 0)
        item.setText(_translate("OrderPage", "Pineapple"))
        item = self.MainMealTable.item(8, 1)
        item.setText(_translate("OrderPage", "Main Meal"))
        item = self.MainMealTable.item(8, 2)
        item.setText(_translate("OrderPage", "Main Course"))
        item = self.MainMealTable.item(8, 3)
        item.setText(_translate("OrderPage", "350"))
        item = self.MainMealTable.item(8, 4)
        item.setText(_translate("OrderPage", "5%"))
        item = self.MainMealTable.item(9, 0)
        item.setText(_translate("OrderPage", "Beef"))
        item = self.MainMealTable.item(9, 1)
        item.setText(_translate("OrderPage", "Main Meal"))
        item = self.MainMealTable.item(9, 2)
        item.setText(_translate("OrderPage", "Main Course"))
        item = self.MainMealTable.item(9, 3)
        item.setText(_translate("OrderPage", "350"))
        item = self.MainMealTable.item(9, 4)
        item.setText(_translate("OrderPage", "4%"))
        self.MainMealTable.setSortingEnabled(__sortingEnabled)
        self.OrderTabs.setTabText(self.OrderTabs.indexOf(self.MainMeal), _translate("OrderPage", "Main Meal"))
        item = self.DrinksTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderPage", "Item Name"))
        item = self.DrinksTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderPage", "Item Category"))
        item = self.DrinksTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderPage", "Item Description"))
        item = self.DrinksTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderPage", "Item Price"))
        item = self.DrinksTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderPage", "Item Tax"))
        __sortingEnabled = self.DrinksTable.isSortingEnabled()
        self.DrinksTable.setSortingEnabled(False)
        item = self.DrinksTable.item(0, 0)
        item.setText(_translate("OrderPage", "Banana Juice"))
        item = self.DrinksTable.item(0, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(0, 2)
        item.setText(_translate("OrderPage", "Beverage"))
        item = self.DrinksTable.item(0, 3)
        item.setText(_translate("OrderPage", "120"))
        item = self.DrinksTable.item(0, 4)
        item.setText(_translate("OrderPage", "3%"))
        item = self.DrinksTable.item(1, 0)
        item.setText(_translate("OrderPage", "Capuccino Coffee"))
        item = self.DrinksTable.item(1, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(1, 2)
        item.setText(_translate("OrderPage", "Hot Drink"))
        item = self.DrinksTable.item(1, 3)
        item.setText(_translate("OrderPage", "100"))
        item = self.DrinksTable.item(1, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.DrinksTable.item(2, 0)
        item.setText(_translate("OrderPage", "Latte Coffee"))
        item = self.DrinksTable.item(2, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(2, 2)
        item.setText(_translate("OrderPage", "Hot Drink"))
        item = self.DrinksTable.item(2, 3)
        item.setText(_translate("OrderPage", "100"))
        item = self.DrinksTable.item(2, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.DrinksTable.item(3, 0)
        item.setText(_translate("OrderPage", "Mocha Coffee"))
        item = self.DrinksTable.item(3, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(3, 2)
        item.setText(_translate("OrderPage", "Hot Drink"))
        item = self.DrinksTable.item(3, 3)
        item.setText(_translate("OrderPage", "100 "))
        item = self.DrinksTable.item(3, 4)
        item.setText(_translate("OrderPage", "1%"))
        item = self.DrinksTable.item(4, 0)
        item.setText(_translate("OrderPage", "Espresso Coffee"))
        item = self.DrinksTable.item(4, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(4, 2)
        item.setText(_translate("OrderPage", "Hot Drink"))
        item = self.DrinksTable.item(4, 3)
        item.setText(_translate("OrderPage", "100"))
        item = self.DrinksTable.item(4, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.DrinksTable.item(5, 0)
        item.setText(_translate("OrderPage", "Ice Coffee"))
        item = self.DrinksTable.item(5, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(5, 2)
        item.setText(_translate("OrderPage", "Hot Drink"))
        item = self.DrinksTable.item(5, 3)
        item.setText(_translate("OrderPage", "100"))
        item = self.DrinksTable.item(5, 4)
        item.setText(_translate("OrderPage", "1.5%"))
        item = self.DrinksTable.item(6, 0)
        item.setText(_translate("OrderPage", "Apple Juice"))
        item = self.DrinksTable.item(6, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(6, 2)
        item.setText(_translate("OrderPage", "Beverage"))
        item = self.DrinksTable.item(6, 3)
        item.setText(_translate("OrderPage", "140"))
        item = self.DrinksTable.item(6, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.DrinksTable.item(7, 0)
        item.setText(_translate("OrderPage", "Strawberry Juice"))
        item = self.DrinksTable.item(7, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(7, 2)
        item.setText(_translate("OrderPage", "Beverage"))
        item = self.DrinksTable.item(7, 3)
        item.setText(_translate("OrderPage", "140"))
        item = self.DrinksTable.item(7, 4)
        item.setText(_translate("OrderPage", "4%"))
        item = self.DrinksTable.item(8, 0)
        item.setText(_translate("OrderPage", "Mango Juice"))
        item = self.DrinksTable.item(8, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(8, 2)
        item.setText(_translate("OrderPage", "Beverage"))
        item = self.DrinksTable.item(8, 3)
        item.setText(_translate("OrderPage", "140"))
        item = self.DrinksTable.item(8, 4)
        item.setText(_translate("OrderPage", "2.5%"))
        item = self.DrinksTable.item(9, 0)
        item.setText(_translate("OrderPage", "Pineapple Juice"))
        item = self.DrinksTable.item(9, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(9, 2)
        item.setText(_translate("OrderPage", "Beverage"))
        item = self.DrinksTable.item(9, 3)
        item.setText(_translate("OrderPage", "120"))
        item = self.DrinksTable.item(9, 4)
        item.setText(_translate("OrderPage", "3%"))
        item = self.DrinksTable.item(10, 0)
        item.setText(_translate("OrderPage", "Pomegranate Juice"))
        item = self.DrinksTable.item(10, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(10, 2)
        item.setText(_translate("OrderPage", "Beverage"))
        item = self.DrinksTable.item(10, 3)
        item.setText(_translate("OrderPage", "140"))
        item = self.DrinksTable.item(10, 4)
        item.setText(_translate("OrderPage", "1.5%"))
        item = self.DrinksTable.item(11, 0)
        item.setText(_translate("OrderPage", "Orange Juice"))
        item = self.DrinksTable.item(11, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(11, 2)
        item.setText(_translate("OrderPage", "Beverage"))
        item = self.DrinksTable.item(11, 3)
        item.setText(_translate("OrderPage", "140"))
        item = self.DrinksTable.item(11, 4)
        item.setText(_translate("OrderPage", "1.5%"))
        item = self.DrinksTable.item(12, 0)
        item.setText(_translate("OrderPage", "Chocolate Milkshake"))
        item = self.DrinksTable.item(12, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(12, 2)
        item.setText(_translate("OrderPage", "Beverage"))
        item = self.DrinksTable.item(12, 3)
        item.setText(_translate("OrderPage", "130"))
        item = self.DrinksTable.item(12, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.DrinksTable.item(13, 0)
        item.setText(_translate("OrderPage", "Kiwi Juice"))
        item = self.DrinksTable.item(13, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(13, 2)
        item.setText(_translate("OrderPage", "Beverage"))
        item = self.DrinksTable.item(13, 3)
        item.setText(_translate("OrderPage", "120"))
        item = self.DrinksTable.item(13, 4)
        item.setText(_translate("OrderPage", "4%"))
        item = self.DrinksTable.item(14, 0)
        item.setText(_translate("OrderPage", "Coffee"))
        item = self.DrinksTable.item(14, 1)
        item.setText(_translate("OrderPage", "Drinks"))
        item = self.DrinksTable.item(14, 2)
        item.setText(_translate("OrderPage", "Hot Drink"))
        item = self.DrinksTable.item(14, 3)
        item.setText(_translate("OrderPage", "100"))
        item = self.DrinksTable.item(14, 4)
        item.setText(_translate("OrderPage", "3%"))
        self.DrinksTable.setSortingEnabled(__sortingEnabled)
        self.OrderTabs.setTabText(self.OrderTabs.indexOf(self.Drinks), _translate("OrderPage", "Drinks"))
        item = self.SnacksTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderPage", "Item Name"))
        item = self.SnacksTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderPage", "Item Category"))
        item = self.SnacksTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderPage", "Item Description"))
        item = self.SnacksTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderPage", "Item Price"))
        item = self.SnacksTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderPage", "Item Tax"))
        __sortingEnabled = self.SnacksTable.isSortingEnabled()
        self.SnacksTable.setSortingEnabled(False)
        item = self.SnacksTable.item(0, 0)
        item.setText(_translate("OrderPage", "Chicken Soup"))
        item = self.SnacksTable.item(0, 1)
        item.setText(_translate("OrderPage", "Snack"))
        item = self.SnacksTable.item(0, 2)
        item.setText(_translate("OrderPage", "Light Food"))
        item = self.SnacksTable.item(0, 3)
        item.setText(_translate("OrderPage", "200"))
        item = self.SnacksTable.item(0, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.SnacksTable.item(1, 0)
        item.setText(_translate("OrderPage", "Vegetable Soup"))
        item = self.SnacksTable.item(1, 1)
        item.setText(_translate("OrderPage", "Snack"))
        item = self.SnacksTable.item(1, 2)
        item.setText(_translate("OrderPage", "Light Food"))
        item = self.SnacksTable.item(1, 3)
        item.setText(_translate("OrderPage", "250"))
        item = self.SnacksTable.item(1, 4)
        item.setText(_translate("OrderPage", "3%"))
        item = self.SnacksTable.item(2, 0)
        item.setText(_translate("OrderPage", "Tomato Soup"))
        item = self.SnacksTable.item(2, 1)
        item.setText(_translate("OrderPage", "Snack"))
        item = self.SnacksTable.item(2, 2)
        item.setText(_translate("OrderPage", "Light Food"))
        item = self.SnacksTable.item(2, 3)
        item.setText(_translate("OrderPage", "200"))
        item = self.SnacksTable.item(2, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.SnacksTable.item(3, 0)
        item.setText(_translate("OrderPage", "Peas Soup"))
        item = self.SnacksTable.item(3, 1)
        item.setText(_translate("OrderPage", "Snack"))
        item = self.SnacksTable.item(3, 2)
        item.setText(_translate("OrderPage", "Light Food"))
        item = self.SnacksTable.item(3, 3)
        item.setText(_translate("OrderPage", "150"))
        item = self.SnacksTable.item(3, 4)
        item.setText(_translate("OrderPage", "1.5%"))
        self.SnacksTable.setSortingEnabled(__sortingEnabled)
        self.OrderTabs.setTabText(self.OrderTabs.indexOf(self.Snacks), _translate("OrderPage", "Snacks"))
        item = self.DesertsTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderPage", "Item Name"))
        item = self.DesertsTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderPage", "Item Description"))
        item = self.DesertsTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderPage", "New Column"))
        item = self.DesertsTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderPage", "Item Price"))
        item = self.DesertsTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderPage", "Item Tax"))
        __sortingEnabled = self.DesertsTable.isSortingEnabled()
        self.DesertsTable.setSortingEnabled(False)
        item = self.DesertsTable.item(0, 0)
        item.setText(_translate("OrderPage", "Ice Cream"))
        item = self.DesertsTable.item(0, 1)
        item.setText(_translate("OrderPage", "Dessert"))
        item = self.DesertsTable.item(0, 2)
        item.setText(_translate("OrderPage", "Delicacy"))
        item = self.DesertsTable.item(0, 3)
        item.setText(_translate("OrderPage", "100"))
        item = self.DesertsTable.item(0, 4)
        item.setText(_translate("OrderPage", "3%"))
        item = self.DesertsTable.item(1, 0)
        item.setText(_translate("OrderPage", "Shir Yakh"))
        item = self.DesertsTable.item(1, 1)
        item.setText(_translate("OrderPage", "Dessert"))
        item = self.DesertsTable.item(1, 2)
        item.setText(_translate("OrderPage", "Delicacy"))
        item = self.DesertsTable.item(1, 3)
        item.setText(_translate("OrderPage", "100"))
        item = self.DesertsTable.item(1, 4)
        item.setText(_translate("OrderPage", "3%"))
        item = self.DesertsTable.item(2, 0)
        item.setText(_translate("OrderPage", "Baghlawa"))
        item = self.DesertsTable.item(2, 1)
        item.setText(_translate("OrderPage", "Dessert"))
        item = self.DesertsTable.item(2, 2)
        item.setText(_translate("OrderPage", "Delicacy"))
        item = self.DesertsTable.item(2, 3)
        item.setText(_translate("OrderPage", "100"))
        item = self.DesertsTable.item(2, 4)
        item.setText(_translate("OrderPage", "4%"))
        item = self.DesertsTable.item(3, 0)
        item.setText(_translate("OrderPage", "Halwa"))
        item = self.DesertsTable.item(3, 1)
        item.setText(_translate("OrderPage", "Dessert"))
        item = self.DesertsTable.item(3, 2)
        item.setText(_translate("OrderPage", "Traditional Delicacy"))
        item = self.DesertsTable.item(3, 3)
        item.setText(_translate("OrderPage", "150"))
        item = self.DesertsTable.item(3, 4)
        item.setText(_translate("OrderPage", "3%"))
        self.DesertsTable.setSortingEnabled(__sortingEnabled)
        self.OrderTabs.setTabText(self.OrderTabs.indexOf(self.Deserts), _translate("OrderPage", "Desserts"))
        item = self.BundlesTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderPage", "Item Name"))
        item = self.BundlesTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderPage", "Item Category"))
        item = self.BundlesTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderPage", "Item Description"))
        item = self.BundlesTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderPage", "Item Price"))
        item = self.BundlesTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderPage", "Item Tax"))
        __sortingEnabled = self.BundlesTable.isSortingEnabled()
        self.BundlesTable.setSortingEnabled(False)
        item = self.BundlesTable.item(0, 0)
        item.setText(_translate("OrderPage", "Zinger Burger"))
        item = self.BundlesTable.item(0, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(0, 2)
        item.setText(_translate("OrderPage", "Fast Food"))
        item = self.BundlesTable.item(0, 3)
        item.setText(_translate("OrderPage", "180"))
        item = self.BundlesTable.item(0, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.BundlesTable.item(1, 0)
        item.setText(_translate("OrderPage", "Beef Burger"))
        item = self.BundlesTable.item(1, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(1, 2)
        item.setText(_translate("OrderPage", "Fast Food"))
        item = self.BundlesTable.item(1, 3)
        item.setText(_translate("OrderPage", "200"))
        item = self.BundlesTable.item(1, 4)
        item.setText(_translate("OrderPage", "4%"))
        item = self.BundlesTable.item(2, 0)
        item.setText(_translate("OrderPage", "Chicken Burger"))
        item = self.BundlesTable.item(2, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(2, 2)
        item.setText(_translate("OrderPage", "Fast Food"))
        item = self.BundlesTable.item(2, 3)
        item.setText(_translate("OrderPage", "200"))
        item = self.BundlesTable.item(2, 4)
        item.setText(_translate("OrderPage", "1.3%"))
        item = self.BundlesTable.item(3, 0)
        item.setText(_translate("OrderPage", "Fish Burger"))
        item = self.BundlesTable.item(3, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(3, 2)
        item.setText(_translate("OrderPage", "Fast Food"))
        item = self.BundlesTable.item(3, 3)
        item.setText(_translate("OrderPage", "220"))
        item = self.BundlesTable.item(3, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.BundlesTable.item(4, 0)
        item.setText(_translate("OrderPage", "King Size"))
        item = self.BundlesTable.item(4, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(4, 2)
        item.setText(_translate("OrderPage", "Fast Food"))
        item = self.BundlesTable.item(4, 3)
        item.setText(_translate("OrderPage", "290"))
        item = self.BundlesTable.item(4, 4)
        item.setText(_translate("OrderPage", "1.5%"))
        item = self.BundlesTable.item(5, 0)
        item.setText(_translate("OrderPage", "Fried Chicken"))
        item = self.BundlesTable.item(5, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(5, 2)
        item.setText(_translate("OrderPage", "Two Pieces"))
        item = self.BundlesTable.item(5, 3)
        item.setText(_translate("OrderPage", "200"))
        item = self.BundlesTable.item(5, 4)
        item.setText(_translate("OrderPage", "1.5%"))
        item = self.BundlesTable.item(6, 0)
        item.setText(_translate("OrderPage", "Chicken Wings"))
        item = self.BundlesTable.item(6, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(6, 2)
        item.setText(_translate("OrderPage", "12 Pieces"))
        item = self.BundlesTable.item(6, 3)
        item.setText(_translate("OrderPage", "190"))
        item = self.BundlesTable.item(6, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.BundlesTable.item(7, 0)
        item.setText(_translate("OrderPage", "Fish Fry"))
        item = self.BundlesTable.item(7, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(7, 2)
        item.setText(_translate("OrderPage", "Fried"))
        item = self.BundlesTable.item(7, 3)
        item.setText(_translate("OrderPage", "230"))
        item = self.BundlesTable.item(7, 4)
        item.setText(_translate("OrderPage", "3%"))
        item = self.BundlesTable.item(8, 0)
        item.setText(_translate("OrderPage", "Nuggets"))
        item = self.BundlesTable.item(8, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(8, 2)
        item.setText(_translate("OrderPage", "6 pieces"))
        item = self.BundlesTable.item(8, 3)
        item.setText(_translate("OrderPage", "160"))
        item = self.BundlesTable.item(8, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.BundlesTable.item(9, 0)
        item.setText(_translate("OrderPage", "Chicken Tenders"))
        item = self.BundlesTable.item(9, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(9, 2)
        item.setText(_translate("OrderPage", "Fried"))
        item = self.BundlesTable.item(9, 3)
        item.setText(_translate("OrderPage", "200"))
        item = self.BundlesTable.item(9, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.BundlesTable.item(10, 0)
        item.setText(_translate("OrderPage", "Fish Tenders"))
        item = self.BundlesTable.item(10, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(10, 2)
        item.setText(_translate("OrderPage", "Fried"))
        item = self.BundlesTable.item(10, 3)
        item.setText(_translate("OrderPage", "230"))
        item = self.BundlesTable.item(10, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.BundlesTable.item(11, 0)
        item.setText(_translate("OrderPage", "Chicken Popcorn"))
        item = self.BundlesTable.item(11, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(11, 2)
        item.setText(_translate("OrderPage", "Fried "))
        item = self.BundlesTable.item(11, 3)
        item.setText(_translate("OrderPage", "160"))
        item = self.BundlesTable.item(11, 4)
        item.setText(_translate("OrderPage", "1.5%"))
        item = self.BundlesTable.item(12, 0)
        item.setText(_translate("OrderPage", "Fish Popcorn"))
        item = self.BundlesTable.item(12, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(12, 2)
        item.setText(_translate("OrderPage", "Fried"))
        item = self.BundlesTable.item(12, 3)
        item.setText(_translate("OrderPage", "160"))
        item = self.BundlesTable.item(12, 4)
        item.setText(_translate("OrderPage", "2%"))
        item = self.BundlesTable.item(13, 0)
        item.setText(_translate("OrderPage", "French Fries"))
        item = self.BundlesTable.item(13, 1)
        item.setText(_translate("OrderPage", "Bundles"))
        item = self.BundlesTable.item(13, 2)
        item.setText(_translate("OrderPage", "Fried"))
        item = self.BundlesTable.item(13, 3)
        item.setText(_translate("OrderPage", "80"))
        item = self.BundlesTable.item(13, 4)
        item.setText(_translate("OrderPage", "1.5%"))
        self.BundlesTable.setSortingEnabled(__sortingEnabled)
        self.OrderTabs.setTabText(self.OrderTabs.indexOf(self.Bundles), _translate("OrderPage", "Bundles"))
        item = self.CartTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderPage", "Item Name"))
        item = self.CartTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderPage", "Item Quantity"))
        item = self.CartTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderPage", "Item Tax"))

        item = self.CartTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderPage", "Item Price"))
        item = self.CartTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderPage", "Total Price"))
        item = self.CartTable.horizontalHeaderItem(5)
        item.setText(_translate("OrderPage", "Category"))
        self.RegisterButton_2.setText(_translate("OrderPage", "Add Order"))
        self.LoginButton.setText(_translate("OrderPage", "Submit Order"))
        self.RegisterButton.setText(_translate("OrderPage", "Clear"))
        self.LoginTitle.setText(_translate("OrderPage",
                                           "<html><head/><body><p><span style=\" font-size:48pt; font-weight:600; color:#f25234;\">Order Page</span></p></body></html>"))


import background_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    OrderPage = QtWidgets.QMainWindow()
    ui = Ui_OrderPage()
    ui.setupUi(OrderPage)
    OrderPage.show()
    sys.exit(app.exec_())
